version: "3.8"

services:


  db:
    image: mysql:8.0.30
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root

      - MYSQL_PASSWORD=worderdb123
      - MYSQL_ROOT_PASSWORD=worderdb123

      - MYSQL_DATABASE=worder
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask:
    build:
      ./worder
    depends_on:
      - db
    restart: on-failure
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - ./:/src

  
volumes:
  db:
    driver: local